# #####################################################################
# Automatically generated by qmake (2.01a) Wed Mar 10 16:53:48 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
RC_FILE = phoneNumberTracker.rc
# Input
HEADERS += phoneTracker.h
FORMS += phone.ui
SOURCES += phoneTracker.cpp
OTHER_FILES += phoneNumberTracker.rc
