######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 10 16:53:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += phoneTracker.h
FORMS += phone.ui
SOURCES += phoneTracker.cpp
